// frontend/hes-system-frontend/src/components/auth/Login.tsx
import { useState, useEffect } from 'react'
import { RefreshCw } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import '../i18n'
import { usePerformanceMonitoring, measureApiResponse } from '@/utils/performance'

export default function Login() {
  usePerformanceMonitoring()
  const { t, i18n } = useTranslation()
  const [accountId, setAccountId] = useState('')
  const [password, setPassword] = useState('')
  const [verificationCode, setVerificationCode] = useState('')
  const [verificationProblem, setVerificationProblem] = useState('')
  const [verificationId, setVerificationId] = useState('')
  const [rememberMe, setRememberMe] = useState(false)
  const [language, setLanguage] = useState(localStorage.getItem('preferredLanguage') || 'en')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)

  const fetchVerificationProblem = async () => {
    try {
      const { response } = await measureApiResponse(`${import.meta.env.VITE_API_URL}/api/v1/auth/verification-code`)
      if (response.ok) {
        const data = await response.json()
        setVerificationProblem(data.problem)
        setVerificationId(data.id)
        setVerificationCode('')
      }
    } catch (error) {
      console.error('Failed to fetch verification code:', error)
    }
  }

  useEffect(() => {
    fetchVerificationProblem()
    const savedAccountId = localStorage.getItem('accountId')
    if (savedAccountId) {
      setAccountId(savedAccountId)
      setRememberMe(true)
    }
  }, [])

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setError('')
    setLoading(true)

    try {
      const { response } = await measureApiResponse(`${import.meta.env.VITE_API_URL}/api/v1/auth/login`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          account_id: accountId,
          password,
          verification_code: verificationCode,
          verification_id: verificationId,
          remember_me: rememberMe
        }),
      })

      const data = await response.json()

      if (response.ok) {
        localStorage.setItem('token', data.access_token)
        if (rememberMe) {
          localStorage.setItem('accountId', accountId)
        } else {
          localStorage.removeItem('accountId')
        }
        window.location.href = '/dashboard'
      } else {
        setError(data.detail || t('login.error.generic'))
        fetchVerificationProblem()
      }
    } catch (error) {
      setError(t('login.error.network'))
    } finally {
      setLoading(false)
    }
  }

  const handleLanguageChange = (lang: string) => {
    i18n.changeLanguage(lang)
    localStorage.setItem('preferredLanguage', lang)
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-md w-full space-y-8">
        <div>
          <h2 className="mt-6 text-center text-3xl font-extrabold text-gray-900">
            {t('login.title')}
          </h2>
        </div>
        <form className="mt-8 space-y-6" onSubmit={handleSubmit}>
          <div className="rounded-md shadow-sm -space-y-px">
            <div className="mb-4">
              <label className="block text-sm font-medium text-gray-700">{t('login.accountId')}</label>
              <input
                type="text"
                value={accountId}
                onChange={(e) => setAccountId(e.target.value)}
                pattern="^[A-Za-z_]{6,25}$"
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                required
                placeholder={t('login.accountIdPlaceholder')}
              />
            </div>

            <div className="mb-4">
              <label className="block text-sm font-medium text-gray-700">{t('login.password')}</label>
              <input
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                minLength={6}
                maxLength={25}
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                required
              />
            </div>

            <div className="mb-4">
              <label className="block text-sm font-medium text-gray-700">{t('login.verificationCode')}</label>
              <div className="flex space-x-2">
                <input
                  type="text"
                  value={verificationCode}
                  onChange={(e) => setVerificationCode(e.target.value)}
                  className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                  placeholder={verificationProblem}
                  required
                />
                <button
                  type="button"
                  onClick={fetchVerificationProblem}
                  className="mt-1 inline-flex items-center px-3 py-2 border border-gray-300 shadow-sm text-sm leading-4 font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                >
                  <RefreshCw className="h-4 w-4" />
                </button>
              </div>
            </div>
          </div>

          <div className="flex items-center justify-between">
            <div className="flex items-center">
              <input
                id="remember-me"
                name="remember-me"
                type="checkbox"
                checked={rememberMe}
                onChange={(e) => setRememberMe(e.target.checked)}
                className="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded"
              />
              <label htmlFor="remember-me" className="ml-2 block text-sm text-gray-900">
                {t('login.rememberMe')}
              </label>
            </div>

            <div className="flex items-center">
              <select
                value={language}
                onChange={(e) => handleLanguageChange(e.target.value)}
                className="mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md"
              >
                <option value="en">English</option>
                <option value="zh">中文</option>
              </select>
            </div>
          </div>

          {error && (
            <div className="rounded-md bg-red-50 p-4">
              <div className="text-sm text-red-700">{error}</div>
            </div>
          )}

          <button
            type="submit"
            disabled={loading}
            className="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:opacity-50"
          >
            {loading ? t('login.loggingIn') : t('login.submit')}
          </button>
        </form>
      </div>
    </div>
  )
}

// frontend/hes-system-frontend-vue/src/components/auth/Login.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { usePerformanceMonitoring } from '@/composables/usePerformanceMonitoring'
import apiClient from '@/api/client'
import { ElMessage } from 'element-plus'
import 'element-plus/es/components/message/style/css'

const { t } = useI18n()
const { measureApiResponse } = usePerformanceMonitoring()

const accountId = ref('')
const password = ref('')
const verificationCode = ref('')
const verificationProblem = ref('')
const verificationId = ref('')
const rememberMe = ref(false)
const loading = ref(false)

const accountIdError = ref('')
const passwordError = ref('')
const verificationError = ref('')

const validateAccountId = (value: string) => {
  if (!value) {
    accountIdError.value = t('login.error.accountId')
    return false
  }
  const isValid = /^[A-Za-z_]{6,25}$/.test(value)
  accountIdError.value = isValid ? '' : t('login.error.accountId')
  return isValid
}

const validatePassword = (value: string) => {
  if (!value || value.length < 6 || value.length > 25) {
    passwordError.value = t('login.error.password')
    return false
  }
  passwordError.value = ''
  return true
}

const validateVerificationCode = (value: string) => {
  if (!value) {
    verificationError.value = t('login.error.verification')
    return false
  }
  verificationError.value = ''
  return true
}

const fetchVerificationCode = async () => {
  try {
    const { response } = await measureApiResponse('/api/v1/auth/verification-code')
    verificationProblem.value = response.data.problem
    verificationId.value = response.data.id
    verificationCode.value = ''
    verificationError.value = ''
  } catch (err) {
    ElMessage.error(t('login.error.network'))
  }
}

const handleSubmit = async () => {
  const isAccountIdValid = validateAccountId(accountId.value)
  const isPasswordValid = validatePassword(password.value)
  const isVerificationValid = validateVerificationCode(verificationCode.value)

  if (!isAccountIdValid || !isPasswordValid || !isVerificationValid) {
    return
  }

  loading.value = true

  try {
    const { response } = await measureApiResponse('/api/v1/auth/login', {
      method: 'POST',
      data: {
        account_id: accountId.value,
        password: password.value,
        verification_code: verificationCode.value,
        verification_id: verificationId.value,
        remember_me: rememberMe.value
      }
    })

    const { access_token, user } = response.data
    localStorage.setItem('token', access_token)
    localStorage.setItem('user', JSON.stringify(user))
    localStorage.setItem('preferredLanguage', user.preferred_language || 'en')
    
    if (rememberMe.value) {
      localStorage.setItem('accountId', accountId.value)
      localStorage.setItem('rememberMe', 'true')
    } else {
      localStorage.removeItem('accountId')
      localStorage.removeItem('rememberMe')
    }
    
    window.location.href = '/dashboard'
  } catch (err: any) {
    if (err.response?.status === 429) {
      ElMessage.error(t('login.error.tooManyAttempts'))
    } else if (err.response?.status === 401) {
      ElMessage.error(t('login.error.generic'))
    } else {
      ElMessage.error(t('login.error.network'))
    }
    fetchVerificationCode()
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  fetchVerificationCode()
  const savedAccountId = localStorage.getItem('accountId')
  const rememberedMe = localStorage.getItem('rememberMe')
  if (savedAccountId && rememberedMe === 'true') {
    accountId.value = savedAccountId
    rememberMe.value = true
  }
})
</script>

<template>
  <div class="min-h-screen flex items-center justify-center bg-gradient-to-r from-blue-500 to-indigo-600 py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-md w-full bg-white rounded-lg shadow-xl p-8">
      <div class="flex justify-end mb-4">
        <select
          class="px-2 py-1 border rounded-md text-sm"
          :value="$i18n.locale"
          @change="$i18n.locale = $event.target.value"
        >
          <option value="en">English</option>
          <option value="zh">中文</option>
        </select>
      </div>
      <div>
        <h2 class="text-center text-2xl font-bold text-gray-900 mb-8">
          {{ t('login.title') }}
        </h2>
      </div>
      <form class="mt-8 space-y-6" @submit.prevent="handleSubmit">
        <div class="rounded-md shadow-sm -space-y-px">
          <div>
            <label for="account-id" class="sr-only">{{ t('login.accountId') }}</label>
            <input
              id="account-id"
              v-model="accountId"
              type="text"
              required
              autocomplete="username"
              :class="[
                'appearance-none rounded-none relative block w-full px-3 py-2 border placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm',
                accountIdError ? 'border-red-500' : 'border-gray-300'
              ]"
              :placeholder="t('login.accountIdPlaceholder')"
              @input="validateAccountId(accountId)"
              @blur="validateAccountId(accountId)"
            />
            <p v-if="accountIdError" class="mt-1 text-sm text-red-600">{{ accountIdError }}</p>
          </div>
          <div>
            <label for="password" class="sr-only">{{ t('login.password') }}</label>
            <input
              id="password"
              v-model="password"
              type="password"
              required
              autocomplete="current-password"
              :class="[
                'appearance-none rounded-none relative block w-full px-3 py-2 border placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm',
                passwordError ? 'border-red-500' : 'border-gray-300'
              ]"
              :placeholder="t('login.password')"
              @input="validatePassword(password)"
              @blur="validatePassword(password)"
            />
            <p v-if="passwordError" class="mt-1 text-sm text-red-600">{{ passwordError }}</p>
          </div>
          <div class="flex">
            <div class="flex-grow">
              <label for="verification-code" class="sr-only">{{ t('login.verificationCode') }}</label>
              <input
                id="verification-code"
                v-model="verificationCode"
                type="text"
                required
                :class="[
                  'appearance-none rounded-none relative block w-full px-3 py-2 border placeholder-gray-500 text-gray-900 rounded-bl-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm',
                  verificationError ? 'border-red-500' : 'border-gray-300'
                ]"
                :placeholder="t('login.verificationCode')"
                @input="validateVerificationCode(verificationCode)"
                @blur="validateVerificationCode(verificationCode)"
              />
              <p v-if="verificationError" class="mt-1 text-sm text-red-600">{{ verificationError }}</p>
            </div>
            <div class="flex items-center justify-center px-4 border border-l-0 border-gray-300 rounded-br-md bg-gray-50">
              <span class="text-sm text-gray-500">{{ verificationProblem }}</span>
            </div>
          </div>
        </div>

        <div class="flex items-center justify-between">
          <div class="flex items-center">
            <input
              id="remember-me"
              v-model="rememberMe"
              type="checkbox"
              class="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded"
            />
            <label for="remember-me" class="ml-2 block text-sm text-gray-900">
              {{ t('login.rememberMe') }}
            </label>
          </div>
        </div>

        <div>
          <button
            type="submit"
            :disabled="loading"
            class="w-full flex justify-center py-3 px-4 text-sm font-semibold rounded-lg text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 disabled:opacity-50 transition-colors duration-200"
          >
            {{ loading ? t('login.loggingIn') : t('login.submit') }}
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
